# Encoding categorical data

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("customer.csv")

In [22]:
df.head(16)

     review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes
15     Poor        UG        No

In [4]:
df =df.iloc[:,2:]

In [5]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

# Train test split

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(df.iloc[:,0:2],
                                                  df.iloc[:,-1],
                                                  test_size=0.2)

In [7]:
X_train

     review education
24  Average        PG
22     Poor        PG
39     Poor        PG
20  Average    School
38     Good    School
32  Average        UG
46     Poor        PG
47     Good        PG
12     Poor    School
19     Poor        PG
11     Good        UG
2      Good        PG
7      Poor    School
25     Good    School
13  Average    School
23     Good    School
17     Poor        UG
43     Poor        PG
37  Average        PG
4   Average        UG
36     Good        UG
34  Average    School
28     Poor    School
31     Poor    School
48     Good        UG
5   Average    School
10     Good        UG
3      Good        PG
33     Good        PG
45     Poor        PG
27     Poor        PG
42     Good        PG
44  Average        UG
14     Poor        PG
8   Average        UG
0   Average    School
35     Poor    School
16     Poor        UG
15     Poor        UG
6      Good    School

In [8]:
from sklearn.preprocessing import OrdinalEncoder

In [9]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
X_train = X_train.astype(str)
X_test = X_test.astype(str)

In [10]:
oe.fit(X_train)

X_train=oe.transform(X_train)
X_test=oe.transform(X_test)

In [12]:
X_train

array([[1., 2.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [2., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [0., 0.],
       [0., 2.],
       [2., 1.],
       [2., 2.],
       [0., 0.],
       [2., 0.],
       [1., 0.],
       [2., 0.],
       [0., 1.],
       [0., 2.],
       [1., 2.],
       [1., 1.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [0., 0.],
       [2., 1.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.],
       [2., 0.]])

In [13]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

# LabelEncoding

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
le = LabelEncoder()

In [16]:
le.fit(y_train)

LabelEncoder()

In [17]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [18]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [19]:
y_train

array([1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0])

# 1.OneHotEncoding using pandas

In [23]:
df = pd.read_csv("cars.csv")

In [24]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [28]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [29]:
df['brand'].nunique()

32

In [30]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [31]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [35]:
pd.get_dummies(df, columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

# 2. K-1 OneHotEncoding

In [36]:
pd.get_dummies(df, columns=['fuel','owner'], drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

# 3.OneHotEncoding using Sklearn

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:4],
                                                    df.iloc[:,-1],
                                                    test_size=0.2,
                                                    random_state=0)

In [40]:
X_train

           brand  km_driven    fuel         owner
3042     Hyundai      60000     LPG   First Owner
1520        Tata     150000  Diesel   Third Owner
2611     Hyundai     110000  Diesel  Second Owner
3544    Mahindra      28000  Diesel  Second Owner
4138      Maruti      15000  Petrol   First Owner
...          ...        ...     ...           ...
4931        Tata      70000  Diesel   Third Owner
3264        Ford     100000  Diesel  Second Owner
1653     Hyundai      90000  Petrol  Second Owner
2607  Volkswagen      90000  Diesel   First Owner
2732     Hyundai     110000  Petrol   First Owner

[6502 rows x 4 columns]

In [42]:
y_train

3042     375000
1520     150000
2611     459999
3544    1050000
4138     700000
         ...
4931     300000
3264     220000
1653     170000
2607     375000
2732     225000
Name: selling_price, Length: 6502, dtype: int64

In [43]:
from sklearn.preprocessing import OneHotEncoder

In [66]:
ohe = OneHotEncoder(drop='first',dtype=np.int32, sparse_output=False)

In [68]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

In [69]:
X_test_new = ohe.transform(X_test[['fuel','owner']])

In [58]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new)).shape

(6502, 9)

# OneHotEncoding with Top Categories

In [61]:
counts = df['brand'].value_counts()

In [62]:
df['brand'].nunique()
threshold = 100

In [64]:
rplc = counts[counts <= threshold].index

In [65]:
pd.get_dummies(df['brand'].replace(rplc, 'uncommon'))

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,True,False,False,False
8127,False,False,False,False,False,False,False,False,False,True,False,False,False

# Column Transformer for Encoding

In [71]:
from sklearn.compose import ColumnTransformer

In [78]:
df=pd.read_csv("covid_toy.csv")

In [79]:
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [80]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [81]:
from sklearn.impute import SimpleImputer

In [89]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [91]:
transformer.fit_transform(X_train).shape

(80, 7)

In [92]:
transformer.fit_transform(X_test).shape

(20, 7)

In [93]:
X_train_transformed = transformer.fit_transform(X_train)

In [94]:
columns=transformer.get_feature_names_out()

In [95]:
X_train_df=pd.DataFrame(
    X_train_transformed,
    columns=columns,
    index=X_train.index)
X_train_df.head()

,tnf1__fever,tnf2__cough,tnf3__gender_Male,tnf3__city_Delhi,tnf3__city_Kolkata,tnf3__city_Mumbai,remainder__age
19,100.690141,1.0,0.0,0.0,0.0,0.0,42.0
12,99.000000,1.0,0.0,0.0,1.0,0.0,25.0
95,104.000000,0.0,0.0,0.0,0.0,0.0,12.0
29,100.690141,1.0,0.0,0.0,0.0,1.0,34.0
94,100.690141,1.0,1.0,0.0,1.0,0.0,79.0

In [97]:
X_train_df.columns=[col.split("__")[-1]
                    for col in X_train_df.columns]
X_train_df.head()

,fever,cough,gender_Male,city_Delhi,city_Kolkata,city_Mumbai,age
19,100.690141,1.0,0.0,0.0,0.0,0.0,42.0
12,99.000000,1.0,0.0,0.0,1.0,0.0,25.0
95,104.000000,0.0,0.0,0.0,0.0,0.0,12.0
29,100.690141,1.0,0.0,0.0,0.0,1.0,34.0
94,100.690141,1.0,1.0,0.0,1.0,0.0,79.0