In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("play_tennis.csv")
data.head()
data.drop(columns = ['day'],inplace = True)

In [3]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [4]:
# problem 1

# outlook=Sunny, temp=Hot, Humidity=High, wind=Weak
# Play or No Play?

In [5]:
# Solution

# P(Yes | Sunny,Hot,High,Weak)=P(Sunny | Yes)*P(Hot | Yes)*P(High | Yes)*P(Weak | Yes)*P(Yes)

# P(No | Sunny,Hot,High,Weak)=P(Sunny | No)*P(Hot | No)*P(High | No)*P(Weak | No)*P(No)

# Compare and decide using the maximum a posteriori rule

In [6]:
# problem 2

# outlook=Overcast, temp=Cold, Humidity=Low, wind=Weak
# Play or No Play?

In [7]:
# Solution

# P(Yes | Overcast,Cold,Low,Weak)=P(Overcast | Yes)*P(Cold | Yes)*P(Low | Yes)*P(Weak | Yes)*P(Yes)

# P(No | Overcast,Cold,Low,Weak)=P(Overcast | No)*P(Cold | No)*P(Low | No)*P(Weak | No)*P(No)

# Compare and decide using the maximum a posteriori rule

In [8]:
# Training

# Lookup Table (Dictionary)

# Testing

In [9]:
# P(yes)
# P(No)

In [10]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [11]:
py = 9/14
pn = 5/14

In [12]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [13]:
# Outlook

pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [14]:
pon = 0
prn = 2/5
psn = 3/5

poy = 4/9
pry = 3/9
psy = 2/9

In [19]:
# Temp
pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [20]:
PCoolNo=1/5
PHotNo=2/5
PMildNo=2/5

PCoolYes=3/9
PHotYes=2/9
PMildYes=4/9

In [21]:
# Humidity
pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [22]:
PHighNo=4/5
PNormalNo=1/5

PHighYes=3/9
PNormalYes=6/9

In [23]:
# Wind
pd.crosstab(data['wind'],data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [24]:
PStrongNo=3/5
PWeakNo=2/5

PStrongYes=3/9
PWeakYes=6/9

In [32]:
# Outlook=Sunny, Temp=Hot, Humidity=High, Wind=Weak
Pyes = py*psy*PHotYes*PHighYes*PWeakYes
print(Pyes)

0.007054673721340388

In [33]:
Pno = pn*psn*PHotNo*PHighNo*PWeakNo
print(Pno)

0.02742857142857143

In [34]:
# No Play